services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - ./config/.env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - tts-cache:/app/logs # Mount logs subfolder volume
    network_mode: host

volumes:
  tts-cache: